using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GameCult.Caching.MessagePack.Generator
{
    [Generator]
    public class DatabaseEntryMessagePackGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext ctx)
        {
            // Select DatabaseEntry subclass declarations
            var databaseEntryTypes = ctx.SyntaxProvider
                .CreateSyntaxProvider(
                    static (s, _) => s is ClassDeclarationSyntax cds && cds.BaseList != null,
                    static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol(ctx.Node) as INamedTypeSymbol)
                .Where(static s => s is not null)!
                .Select((s, _) => s!)
                .Where(symbol =>
                {
                    if (symbol.IsAbstract) return false;
                    var baseType = symbol.BaseType;
                    while (baseType != null)
                    {
                        if (baseType.ToDisplayString() == "GameCult.Caching.DatabaseEntry")
                            return true;
                        baseType = baseType.BaseType;
                    }
                    return false;
                });

            // 2. Distinct types
            var collected = databaseEntryTypes.Collect();

            // 3. Register output
            ctx.RegisterSourceOutput(collected, (spc, types) =>
            {
                //if (types.Length == 0) return;

                var sbResolvers = new StringBuilder();
                var sbFormatters = new StringBuilder();

                sbResolvers.AppendLine("// <auto-generated/>");
                sbResolvers.AppendLine("using System;");
                sbResolvers.AppendLine("using MessagePack.Formatters;");
                sbResolvers.AppendLine("namespace GameCult.Caching.MessagePack");
                sbResolvers.AppendLine("{");
                sbResolvers.AppendLine("    static partial class GeneratedDatabaseEntryResolvers");
                sbResolvers.AppendLine("    {");
                sbResolvers.AppendLine("        public static IMessagePackFormatter<T>? GetFormatter<T>()");
                sbResolvers.AppendLine("        {");
                sbResolvers.AppendLine("            var t = typeof(T);");

                foreach (var type in types)
                {
                    var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                    var formatterName = $"{Sanitize(type)}__MessagePackFormatter";

                    var fmtSrc = GenerateFormatterFor(type, formatterName);
                    sbFormatters.AppendLine(fmtSrc);

                    sbResolvers.AppendLine(
                        $"            if (t == typeof({fullName})) return (IMessagePackFormatter<T>)(object){formatterName}.Instance;");
                }

                sbResolvers.AppendLine("            return null;");
                sbResolvers.AppendLine("        }");
                sbResolvers.AppendLine("    }");
                sbResolvers.AppendLine("}");

                spc.AddSource("GeneratedDatabaseEntryFormatters.g.cs", SourceText.From(sbFormatters.ToString(), Encoding.UTF8));
                spc.AddSource("GeneratedDatabaseEntryResolvers.g.cs", SourceText.From(sbResolvers.ToString(), Encoding.UTF8));
            });
        }

        private static string Sanitize(ISymbol symbol)
        {
            var s = symbol.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
            return s.Replace(".", "_")
                    .Replace("<", "_")
                    .Replace(">", "_")
                    .Replace(",", "_")
                    .Replace(" ", "_");
        }

        // Collect members, order them, generate the formatter
        private static string GenerateFormatterFor(INamedTypeSymbol type, string formatterName)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using MessagePack;");
            sb.AppendLine("using MessagePack.Formatters;");
            sb.AppendLine();

            var ns = type.ContainingNamespace.IsGlobalNamespace
                ? "GameCult.Caching.Generated"
                : type.ContainingNamespace.ToDisplayString();
            sb.AppendLine($"namespace {ns}");
            sb.AppendLine("{");

            var typeFull = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

            sb.AppendLine($"    internal sealed class {formatterName} : IMessagePackFormatter<{typeFull}>");
            sb.AppendLine("    {");
            sb.AppendLine($"        public static readonly {formatterName} Instance = new {formatterName}();");
            sb.AppendLine("        private {formatterName}() { }");
            sb.AppendLine();

            var members = CollectMembers(type);
            var ordered = OrderMembers(type, members);

            // Serialize
            sb.AppendLine($"        public void Serialize(ref MessagePackWriter writer, {typeFull}? value, MessagePackSerializerOptions options)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (value == null) { writer.WriteNil(); return; }");
            sb.AppendLine($"            writer.WriteArrayHeader({ordered.Count});");
            for (int i = 0; i < ordered.Count; i++)
            {
                var (name, tsym) = ordered[i];
                var tname = tsym.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var access = $"value.{name}";
                sb.AppendLine(
                    tname == "global::System.Guid"
                        ? $"            options.Resolver.GetFormatterWithVerify<System.Guid>().Serialize(ref writer, {access}, options);"
                        : $"            options.Resolver.GetFormatterWithVerify<{tname}>().Serialize(ref writer, {access}, options);");
            }
            sb.AppendLine("        }");

            // Deserialize
            sb.AppendLine();
            sb.AppendLine($"        public {typeFull}? Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)");
            sb.AppendLine("        {");
            sb.AppendLine("            if (reader.TryReadNil()) return null;");
            sb.AppendLine($"            var count = reader.ReadArrayHeader();");
            sb.AppendLine($"            if (count != {ordered.Count}) throw new MessagePackSerializationException($\"Invalid {type.Name} length {{count}}, expected {ordered.Count}\");");
            for (int i = 0; i < ordered.Count; i++)
            {
                var (_, tsym) = ordered[i];
                var tname = tsym.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine(
                    tname == "global::System.Guid"
                        ? $"            var v{i} = options.Resolver.GetFormatterWithVerify<System.Guid>().Deserialize(ref reader, options);"
                        : $"            var v{i} = options.Resolver.GetFormatterWithVerify<{tname}>().Deserialize(ref reader, options);");
            }
            sb.AppendLine($"            var obj = new {typeFull}();");
            for (int i = 0; i < ordered.Count; i++)
            {
                sb.AppendLine($"            obj.{ordered[i].name} = v{i};");
            }
            sb.AppendLine("            return obj;");
            sb.AppendLine("        }");

            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static List<(string name, ITypeSymbol typeSymbol, int? key, bool ignore)> CollectMembers(INamedTypeSymbol type)
        {
            var members = new List<(string, ITypeSymbol, int?, bool)>();

            foreach (var f in type.GetMembers().OfType<IFieldSymbol>())
            {
                if (f.IsStatic) continue;
                var ignore = f.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "MessagePack.IgnoreMemberAttribute");
                var key = GetKeyValue(f);
                members.Add((f.Name, f.Type, key, ignore));
            }

            foreach (var p in type.GetMembers().OfType<IPropertySymbol>())
            {
                if (p.IsStatic || p.SetMethod == null || p.GetMethod == null) continue;
                var ignore = p.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() == "MessagePack.IgnoreMemberAttribute");
                var key = GetKeyValue(p);
                members.Add((p.Name, p.Type, key, ignore));
            }

            return members;
        }

        private static List<(string name, ITypeSymbol typeSymbol)> OrderMembers(
            INamedTypeSymbol type,
            List<(string name, ITypeSymbol typeSymbol, int? key, bool ignore)> members)
        {
            members = members.Where(m => !m.ignore).ToList();

            var ordered = new List<(string, ITypeSymbol)>();

            var id = FindIdMember(type);
            if (id != null)
            {
                ordered.Add((id.Value.name, id.Value.typeSymbol));
                members.RemoveAll(m => m.name == id.Value.name);
            }

            var keyed = members.Where(m => m.key.HasValue).OrderBy(m => m.key.Value)
                               .Select(m => (m.name, m.typeSymbol)).ToList();
            var nonKeyed = members.Where(m => !m.key.HasValue)
                                  .Select(m => (m.name, m.typeSymbol)).ToList();

            ordered.AddRange(keyed);
            ordered.AddRange(nonKeyed);
            return ordered;
        }

        private static int? GetKeyValue(ISymbol sym)
        {
            foreach (var attr in sym.GetAttributes())
            {
                var n = attr.AttributeClass?.ToDisplayString();
                if (n == "MessagePack.KeyAttribute" || n == "MessagePack.Key")
                {
                    if (attr.ConstructorArguments.Length >= 1 && attr.ConstructorArguments[0].Value is int i)
                        return i;
                }
            }
            return null;
        }

        private static (string name, ITypeSymbol typeSymbol)? FindIdMember(INamedTypeSymbol type)
        {
            var cur = type;
            while (cur != null)
            {
                foreach (var f in cur.GetMembers().OfType<IFieldSymbol>())
                {
                    if ((f.Name == "ID") && f.Type.ToDisplayString() == "System.Guid")
                        return (f.Name, f.Type);
                }
                cur = cur.BaseType;
            }
            return null;
        }
    }
}
